project:
  type: website

website:
  title: "Shion Fukuzawa"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/shifubear
format:
  html:
    theme: minty
    css: styles.css

# comments:
#   giscus: 
#     repo: shifubear/shifubear.github.io


