---
title: "Art and AI: A new era for art?"
author: "Shion Fukuzawa"
date: "2023-01-17"
categories: [technology, arts, blog]
---

Last year, OpenAI announced the second version of their text-to-image deep learning model, [Dall-E 2](https://openai.com/dall-e-2/). If you haven't seen it, I encourage you to explore the linked page and check out some of what this model is capable of doing. If you're anything like me, you will be shocked and fascinated at the quality and range of the results the model can produce. I spoke with fellow computer scientists who were surprised by how soon a model of this caliber appeared. Many of us were expecting something like this to appear in the near future, but not so soon (especially considering the level the first [Dall-E](https://openai.com/blog/dall-e/) was at just one year ago). 

I'm hopeful that through maintaining (or creating) a deep connection between the artist and audience, art will not be lost to AI and if anything this is an opportunity for us to sharpen our understanding and ideals for art's role in society. 

It has always been true that it may take a while for someone to discover something new, but once it's found others are able to learn the mechanics fairly quickly. A similar thing can be said about the technology behind Dall-E 2 ([transformers](https://en.wikipedia.org/wiki/Transformer_(machine_learning_model))), and we have seen many alternative services deployed throughout this year for generating images from text prompts. 

Though these can be fun to play around with, there have been many debates surrounding the implications and ethics of using this technology. A quick search for AI art on any social media platform will reveal a wide range of opinions on the matter. 

Before sharing my thoughts, let's take a moment to deconstruct the main critique that is brought up against AI art. The following quote from [Lois van Baarle's instagram post](https://www.instagram.com/p/CmMds1dM__Z/) captures the essence of the frustrations I've seen online: “I wholeheartedly support the ongoing protest against AI art. Why? Because my artwork is included in the datasets used to train these image generators without my consent.” Many of these posts are accompanied by strong anti-AI sentiments and a sense of fear in the comments about the implications of this emerging technology. The core of this critique is against the way these models are being trained and deployed, with the objective being to ban or restrict the usage of these models all together. 

I sympathize with regulating the training data that these models have access to, but I also do not think that there is much we are able to do to stop nefarious players to keep training and publicizing models. There are many counterarguments against the critique above as well, such as saying that the way the models learn from the data is the same as how human artists learn and get inspired from the art they engage with. As a computer scientist, it's hard to object to this argument knowing the way these models learn from data, and how many people in the field believe that the way humans learn can be boiled down to the mechanics of a neural network. Ultimately, this discussion misses the mark of what is important, and instead we should take this opportunity to think about what art means to us and the role we want it to have moving forward. 

## My Thoughts 

As a huge lover of the arts and a budding computer scientist, this battle has been a painful one to watch unfold. However, I am hopeful for the future of art and technology *especially* in light of these conversations. My thoughts on the matter are that technologies like this force us to rethink what art means to us, and what we want it to mean to us moving forward. 

A quick tour through the development of computer science will help motivate my point. Computer science studies *algorithms*, which are a set of instructions for solving different problems. When creating these algorithms, we are forced to think about small decisions we make subconsciously for different tasks. Talk to any new undergraduate in computer science and they will tell you that it takes a lot of thought to tell a computer how to find a number in a list, something you could ask a child to do with three words: "Where is 27?". 

In the process of formalizing this field, an interesting question was posed by Alan Turing. "Is it possible to create a machine such that a person wouldn't be able to distinguish whether it is a human or a machine?" This is referred to as the [Turing test](https://en.wikipedia.org/wiki/Turing_test), and was set up as a major milestone for the field of computer science. Many people agreed that when a machine is able to do this, we will be able to call it "intelligent". 

We proudly label ourselves as an "intelligent" species, but the advance of technology continually forces us to wrestle with what that word means. For example, another "intelligent" pursuit humans have been very proud of is the ability to play chess, at extremely high levels. This is why the victory of Deep Blue against Gary Kasparov spurred conversation from around the dinner table to academic conferences, leading to an uproar about the takeover of AI. 

The Turing test can also be cleared by many large scale language models these days, as was demonstrated by a [Google engineer claiming that an AI chatbot is sentient](https://www.scientificamerican.com/article/google-engineer-claims-ai-chatbot-is-sentient-why-that-matters/). It seems that AI is passing the Turing test for image creation too, as is evident by these articles: [Reddit’s Art Subreddit Shuts Down After Mod Mistakes Real Artist for AI](https://www.gamerevolution.com/news/931803-reddit-art-subreddit-shuts-down-ai-artist-mod-ban), [A Professional Artist Spent 100 Hours Working On This Book Cover Image, Only To Be Accused Of Using AI](https://www.buzzfeednews.com/article/chrisstokelwalker/art-subreddit-illustrator-ai-art-controversy). 

Even though these "feats of intelligence" are now child's play for these models, we refuse to accept that they've become "intelligent". Chess is still extremely popular (arguably [more popular](https://win.gg/news/ludwig-broke-viewership-record-during-chessboxing-event/) [than it's](https://www.chess.com/article/view/chesscom-reaches-100-million-members) [ever been](https://en.wikipedia.org/wiki/PogChamps)) and we don't get excited to share our crazy day to a chatbot. Instead, we realize that these milestones for intelligence didn't really capture the essence of the word. We push the goal post further and, in this process refine our understanding of intelligence and its role in what it means to be human. 

I've learned that part of studying computer science is facing a stream of confrontations on our understanding of intelligence. The reason I keep studying it is because the more I learn, the more my appreciation for the complexity of the human experience increases. I feel a sense of awe similar to when I stare into the depths of the ocean. Each discovery adding a ray of light, forcing us to confront the reality that the bottom is much deeper than we thought.

In a similar way, I feel like we are now being confronted with the opportunity to think about what art is, and the role it plays in our human experience. For me, art is never just about the work itself, but is a bridge for me to connect with others in ways that we can't in conversation. My experiences with art I love are amplified by the stories they carry both explicitly and implicitly. The world the artist was living in when they created the work and the world I'm experiencing, combined, generates a unique perception of the work that only I can really experience. Sure, AI can be trained on large databases of images and mix those in clever ways to create new works but, for me, it's hard to imagine that this will replace the role art plays in our lives. I am confident that when we think deeply about what remains after AI rummages through the space of what we call art, we will come out with a deeper appreciation of what it means to us in the first place. 

At the end of the day, I may practice against a chess bot, but it's so that I can play a great game with my friend the next time we're sitting over a chess board. Chatbots have their useful moments, but what we remember from them are when they fail and we all laugh at the screenshot together. We won't lose art if we take the time to slow down enough to share and listen to each others' stories. 

## A New Era

Still, I do think we are at a moment in art history where a huge shift will occur, both for the artist and the audience. This isn't only because of AI art, but other technologies like social media, video games and streaming services providing a stream of accessible entertainment beyond any caliber of what we have seen before. I'm not an expert in art history, but there are clear markers in time we use to identify art from different eras, and these markers are identified through a mix of stylistic and cultural shifts that influence the art of the time. 

## Concluding Remarks

I thought about this topic for a while before writing it up, and this is now my current response to any questions surrounding art and AI. Sure, it leaves open a lot of questions, like "what is art?", but I think this is a great opportunity for me to slow down and reevaluate the way I interact with art. When I mindlessly scroll through instagram, am I fully appreciating the humanity and stories of the people who created the work? If I play music while I'm studying or at the gym, is that limiting my focus that should be directed at the musicians? My answer to these questions is *no*, as is probably the case for many who are reading this. The quality of a conversation isn't only dictated by the dialogue of the speaker, it requires the presence and attention of the listener. To that end, I want to challenge myself moving forward to wrestle more with this question by taking more time to fully immerse myself in various arts. If AI were to take over art, it'll be when we stop connecting through the experiences. 


